### PR TITLE
Updates module for use with SilverStripe 4

### PR DESCRIPTION
**Pull request by dmcb**

### CODE REVIEW

**Comment by gorriecoe** [comment]
Hey @dmcb,  thanks for the PR.  Have you managed to get this working?  Although its not committed I have updated the module and I'm not able to get mine nor your PR to work.

**Comment by dmcb** [comment]
Hey @gorriecoe, thanks for looking at this. The site I've been building that needed an SS4 version of this module is still behind a firewall, so I don't have imgix connected and able to read my source images on my site, but I do have this module working in that it generates imgix image URLs that _look_ correct. When you say it's not working, what's happening on your end?

**Comment by dmcb** [comment]
Hey @gorriecoe I finally got around to testing the integration and it's definitely working. Let me know what issues you are having.

**Comment by gorriecoe** [comment]
Hey @dmcb,  Myself and the team don't have enough time to manage this module.   Would you like me to transfer ownership to you?

**Comment by dmcb** [comment]
That works for me @gorriecoe, a project we are on will force us to make sure this module is working properly.

**Comment by gorriecoe** [comment]
Ok, I have tried sending you the repo, but can't until your fork is deleted.  So I'll merge this PR.  Can you delete your fork and let me know when I can transfer it?

**Comment by dmcb** [comment]
@gorriecoe I've deleted the fork. Thanks.

**Comment by dmcb** [comment]
@gorriecoe Doesn't look like you've transferred it to me? Did I mess up?

**Pull request merged**
